### ISSUE TITLE
web viewer for converted nifti files

### ISSUE THREAD

**Issue by hanayik** [open-dicom/dicom-gallery#1]
Hi there, 

@neurolabusc suggested it would be nice to link the converted nifti files so that people could see them without downloading. 

To that end, I have updated our NiiVue webGL nifti viewer demos so that a special, hidden page can be used to view images hosted on GitHub pages. 

actions items to make this work:
- go to each repo listed in the gallery table and enable pages on the **main/master** branch and from the **root** of the repo.
- add a column to the table with a link to the file to view
- The link must have the format: `https://niivue.github.io/niivue/features/view.html?url=https://hanayik.github.io/siemens_mprage_0/nii/converted.nii.gz`
- using the format of the link above, just replace the URL string on the right of the equal sign `url=<url_string>`. Here `<url_string>` will be the link to the nifti file you wish to show in the viewer, and it must be from a github pages site, not the git repo itself. 

Happy to help if you have any questions.

**Comment by ZviBaratz** [comment]
@hanayik these instructions worked perfectly, thank you so much!
I updated the two existing repos with the link (open-dicom/siemens_mprage_0#1 and open-dicom/siemens_flair_0#1), as well as the template repo (open-dicom/gallery-template#2), and added the links to the table (#2).
